import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Nav from "./components/Nav";
import SessionProvider from "./components/SessionProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Nav /> {/* ตรงนี้ไม่ต้องเช็ค path */}
          {children}
          <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
        </SessionProvider>
      </body>
    </html>
  );
}
